### ISSUE TITLE
请问Controller和Dangle影响核心功能吗？

### ISSUE THREAD

**Issue by fumingxi** [peng-zhihui/Dummy-Robot#107]
稚晖君好，我这边在尝试复现核心功能，Motor和REF都已经OK了，为了驱动机械臂，我的理解是：
1. Peak主要做交互，不影响功能，使用电脑串口也是可以的？
2. Controller和Dangle非必须，不影响机械臂核心功能？不是很理解这两个板子主要是做什么的

**Comment by peng-zhihui** [comment]
1.是的，串口可以，但是更推荐使用仓库的reftool命令行交互方便得多，可以直接调参和控制每一个电机的行为
2.不影响，Controller是视频中演示的无线6轴力反馈手柄（PS5手柄改造的），Dangle是手柄的电脑端接收器

**Comment by fumingxi** [comment]
> 1.是的，串口可以，但是更推荐使用仓库的reftool命令行交互方便得多，可以直接调参和控制每一个电机的行为 2.不影响，Controller是视频中演示的无线6轴力反馈手柄（PS5手柄改造的），Dangle是手柄的电脑端接收器
> 
> 另外机械臂的标定校准有一些讲究，我平时比较忙，B站上有人已经搞定了，可以跟他交流一下@[江城子1984](https://space.bilibili.com/622926297)

多谢大佬！！！
