### ISSUE TITLE
五相电机 or 两相电机

### ISSUE THREAD

**Issue by little-star-bling-bling** [peng-zhihui/Dummy-Robot#113]
大佬，项目里的电机驱动板是驱动两相步进电机的吧？我看模型里有几处用了五相步进电机，驱动板也能通用吗？

**Comment by peng-zhihui** [comment]
两相的，5相要改驱动不通用

**Comment by fumingxi** [comment]
> 两相的，5相要改驱动不通用

所以step文件中列举的PK543AW-H50S和PK513PA-H50S都被换成了常规的两相电机？

**Comment by peng-zhihui** [comment]
是的

**Comment by StarJi1991** [comment]
> 两相的，5相要改驱动不通用

但我看了下你做的机械手实物图上末端确实用的是H50S，请问稚晖君当时有写5相的驱动吗？我查了下一般都是2相4线，貌似没有5相的开源驱动

**Comment by fumingxi** [comment]
> > 两相的，5相要改驱动不通用
> 
> 但我看了下你做的机械手实物图上末端确实用的是H50S，请问稚晖君当时有写5相的驱动吗？我查了下一般都是2相4线，貌似没有5相的开源驱动

稚晖应该是把后面的步进拆掉了，只用了减速。
我也买了这款准备暴力搞掉它。。。

**Comment by StarJi1991** [comment]
> > > 两相的，5相要改驱动不通用
> > 
> > 
> > 但我看了下你做的机械手实物图上末端确实用的是H50S，请问稚晖君当时有写5相的驱动吗？我查了下一般都是2相4线，貌似没有5相的开源驱动
> 
> 稚晖应该是把后面的步进拆掉了，只用了减速。 我也买了这款准备暴力搞掉它。。。

我也买了打算暴力拆解，但是电机和减速器连得很紧啊，兄弟成功了吗？

**Comment by fumingxi** [comment]
200多买了个博世的角磨机，磨开的。。。
