### ISSUE TITLE
固件下载无法识别芯片

### ISSUE THREAD

**Issue by fumingxi** [peng-zhihui/Dummy-Robot#119]
用ST-Link v2 接42驱动板的GND, CLK, DIO, 板子供3.3v电还是无法找到target.
原理图中有boot 0但是没找到引脚噢。。
第一次下载固件是需要通过两个按键来进入flash模式吗？

求刷成功的大佬指点。

**Comment by peng-zhihui** [comment]
不需要，检查电路焊接，也可能买到国产假芯片了

**Comment by fumingxi** [comment]
> 不需要，检查电路焊接，也可能买到国产假芯片了

好的，谢谢大佬回复
