### ISSUE TITLE
步进电机校准失败

### ISSUE THREAD

**Issue by jzijin** [peng-zhihui/Dummy-Robot#123]
稚晖君，你好：
        我调试电机驱动板的时候发现，校准老是失败。我在OnUartCmd中添加控制校准的代码。上电后通过串口发送'C' 校准电机。当电机正转两圈反转两圈后，检查校准数据失败，CalibrationDataCheck的返回值是CALI_ERROR_AVERAGE_DIR。请问下有可能是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/30747856/162605110-e2c234b5-14c7-47fd-8f35-dd0addedbed7.png)

驱动板和电机的连接是这样的：
![IMG_20220409_140326](https://user-images.githubusercontent.com/30747856/162605095-3c36e06d-1025-4f3a-b665-1291b3a4bddb.jpg)

**Comment by peng-zhihui** [comment]
你都没接磁铁和编码器，校准怎么可能成功呢...驱动板是贴在点击后面的，电机轴上要安装一个径向充磁的磁铁
