### ISSUE TITLE
STM32 Cube IDE 編譯問題 (undefined reference to)

### ISSUE THREAD

**Issue by Kevin75311** [peng-zhihui/Dummy-Robot#160]
我使用 Cube IDE 開啟專案後，編譯時發現無法找到 Userapp/common_inc.h 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/59347832/203896166-5cbdc2e5-e0f4-4f3f-bfec-31bd862820f0.png">
將它加入 compiler include 的 PATH 後，變成 common_inc.h 裡面的 function 無法引用 (undefined reference to)
<img width="779" alt="image" src="https://user-images.githubusercontent.com/59347832/203896378-4b16b7cd-8307-482b-b87a-05a98fb29c6e.png">
想請問是 C 和 C++ 混編造成的問題嗎？ 謝謝！

**Comment by sytnocui** [comment]
我把main.cpp的名字改成 userapp.c 就好使了

**Comment by peng-zhihui** [comment]
改CMakeLists.txt，不要改path，正常应该是有这个包含路径的，CLion里面clear cache and restart试一下
