### ISSUE TITLE
关于使用ref-tool发送movel指令时的问题

### ISSUE THREAD

**Issue by YuNathan-coder** [peng-zhihui/Dummy-Robot#162]
稚晖君，你好，我调试时遇到以下问题，可以帮我解答一下吗
1、使用ref-tool工具发送movel和movej指令时只输出true，但是机械臂不动，对于每个关节发送set-position指令时可以动，
2、使用上位机时可以连接、但是拖动关节时，机械臂也不动
麻烦了谢谢

**Comment by YuNathan-coder** [comment]
![89BBBE3C-D9E3-41B4-A01C-1D97C21CACB0](https://user-images.githubusercontent.com/80801505/208165409-ab2bca41-a62d-4654-bc49-1917eade41bc.png)

**Comment by andrewhutong12345** [comment]
请问是怎么解决的呢

**Comment by bobzuoy** [comment]
我是让 机械臂默认状态下垂，初始状态。

先发送 dummy0.robot.set_enable(1)
然后再发送 dummy0.robot.move_j(-20,-63,100,60,-90,0) 就可以看到机械臂运动了。
复位发送，会返回初始状态。
dummy0.robot.move_j(0,-73,180,0,0,0)
