### ISSUE TITLE
同步现实部分能不能加在真正的中小型机械臂上阿

### ISSUE THREAD

**Issue by ZXin0305** [peng-zhihui/Dummy-Robot#19]
如题，如果可以的话，希望这一部分能够开源，也能够作为比较好的人机交互方式了，大神太强了！！！！

**Comment by ballballu** [comment]
htc 有一个vive tracker。你可以用这个设备和这边的开源代码[vive-tracker](https://github.com/moon-wreckers/vive_tracker)，实现在ros框架下对机械臂的操作。我自己这边是用这个来遥操作ur5、tiago这样的机器人

**Comment by ZXin0305** [comment]
> htc 有一个vive tracker。你可以用这个设备和这边的开源代码[vive-tracker](https://github.com/moon-wreckers/vive_tracker)，实现在ros框架下对机械臂的操作。我自己这边是用这个来遥操作ur5、tia

**Comment by ZXin0305** [comment]
> htc 有一个vive tracker。你可以用这个设备和这边的开源代码[vive-tracker](https://github.com/moon-wreckers/vive_tracker)，实现在ros框架下对机械臂的操作。我自己这边是用这个来遥操作ur5、tiago这样的机器人

多谢，有时间去试一试
