### ISSUE TITLE
有兴趣开源ps5力反馈扳机的相关代码么

### ISSUE THREAD

**Issue by ballballu** [peng-zhihui/Dummy-Robot#26]
今年2月做手持力反馈装置的时候考虑过ps5那个扳机，结果不是很理想。今年看了大佬做的这个，感觉好像很不错

**Comment by peng-zhihui** [comment]
PS5手柄的扳机改造是把零件上的所有硬件连接到自己的PCB上控制反馈，相当于换主控，具体可以参考我发的原理图PCB

**Comment by peng-zhihui** [comment]
代码开发时间原因其实实现得还很简单，就是几个PID控制环，这种反馈的效果主要受限于硬件，所以用PS5的硬件做效果可以很好
