### ISSUE TITLE
Joint 1:1 和Base之间有一个螺丝孔可能导出的时候出问题了，建议直接放原始设计文件

### ISSUE THREAD

**Issue by DanZhang6** [peng-zhihui/Dummy-Robot#36]
![Issue](https://i.loli.net/2021/10/10/weqlMGthFiELKna.png)

**Comment by Hconk** [comment]
应该是Shape3D的bug， 导出的模型在SW、Rhino、Fusion 360里面显示都正常，只有Shape3d显示不对，作者用的fusion 360, 如果导出他的专用格式f3d其他软件是打不开的，step格式更通用一些。

**Comment by DanZhang6** [comment]
嗯嗯，在Fusion360里看了，那就应该是shapr3D导入产生的错误，多谢！
