### ISSUE TITLE
咨询zhihui兄，从事这些DIY平时的资金投入情况

### ISSUE THREAD

**Issue by jpixy** [peng-zhihui/Dummy-Robot#38]
很久之前，几乎是从zhihui君在大学时候作寻线机器人开始，就一直关注zhihui兄的DIY，也深受启发。

我最大的问题是，其实zhihui兄之前也曾透露过花过不少钱，但是一直没有一个具体的数量级。

所以，还是希望zhihui兄能否大概给出个从入门到平时开发的大体的资金投入，个人想得以参考：

1. 原材料的费用，小的电子元器件估计费用不大，但是一些CPU等重要芯片和制作PCB板子，和作废板子等费用应该投入不小(每次小几百，小一千，累积多了也不少费用估计)，能否具体说说？
2. 这个机械臂成品费用一万元左右，但是从开发到设计，debug，作废等考虑进去，总计会投入多少？
3. 由此，针对一般的DIY的开发，资金投入分布大概什么样子呢？比如作废板子大概占6,7成总费用等。能否给出个资金占比？当然详单更好。
4. 除了这些，那些工具一次性的投入，估计还好。不管是焊台，还是3D打印机基本上都是一次性投入，这部分也能出个大概的清单吗？
5. 总而言之，想知道zhihui兄，平时维持这个DIY爱好，资金投入的大体情况，以供参考。

不知道这个是不是敏感话题，之前在给您的个人邮箱pengzhihui.david@foxmail.com 发过邮件咨询类似问题。如果不方便在issue里公开回答，是否可以邮件给我: johnny@jpixy.com一些指导和答复？

谢谢！
Johnny

**Comment by peng-zhihui** [comment]
1. 元器件库是持续积累的，比如可以去买一个电阻电容本，型号很全性价比也很高，除了最近出现的芯片涨上天的情况，其余器件有个1、2000元足够囤一堆了
2. 费用主要就是减速器和PCB打样，详细的没算，总之不超过2w吧
3. 上面说了，可以屯一个元件库，根据项目持续补充
4. 我以前报道里说过，我在大学为了买工具和元件做比赛，连饭都吃不起了，而我生活费也才一个月1000当时也做出了很多有意思的东西；所以投入这种事情往上了看就不封顶了，我条件好了之后买工具都是很舍得投入的，但是往下看，只要每月有个几百块也完全足够。
