### ISSUE TITLE
关于位置的记忆，每次上电都需要零点校准吗？

### ISSUE THREAD

**Issue by eqio** [peng-zhihui/Dummy-Robot#40]
我的理解是步进的绝对位置是从上电开始计算的。在断电后是否需要归零，6个轴是分别校准的吗？

**Comment by peng-zhihui** [comment]
绝对位置只在一圈内有效，经过减速后为了获取绝对位置一般是做输出端编码，但是这样精度就降低了30倍（减速比），所以更合理的是做双编码器，而我这个项目中双编码器影响结构紧凑设计，所以用了更巧妙的方式：利用电机驱动的电流环控制上电后进行低力矩的无零点定向运动，碰到机械臂限位之后确认零点。这个方式的零点是没有误差的，而且几乎不受加工精度影响，因为在12度（360/30）内都是绝对值编码器的有效精度范围。

**Comment by eqio** [comment]
@peng-zhihui 小系统而言，您的实现已经很巧妙了。只是实际应用中限位开关好像也是必须的，且不一定每次能去零点校准，也许有工件。商业应用是另一个范畴，个人觉得。

**Comment by zhbi98** [comment]
为什么 Dummy 要设置两次零点？第一次是 L 形的时候设置一下，复位姿势后在设置一下。在机械臂回到休息姿势（Resting Pose）后再应用一次“当前位置作为零点”（ApplyPositionAsHome），那么最后零点不就会以休息姿势来定义

![Image](https://github.com/user-attachments/assets/7c6dc557-fede-464d-9a3c-5659a2027bd4)
