### ISSUE TITLE
偶像能不能把上位机软件的项目代码也开源呀，想要学习学习

### ISSUE THREAD

**Issue by nishiwodelian** [peng-zhihui/Dummy-Robot#54]
感谢

**Comment by HackEFA** [comment]
[Assembly-CSharp.zip](https://github.com/peng-zhihui/Dummy-Robot/files/7345792/Assembly-CSharp.zip)
SW: dnSpy
需要增加unity引擎引用

**Comment by nishiwodelian** [comment]
> [Assembly-CSharp.zip](https://github.com/peng-zhihui/Dummy-Robot/files/7345792/Assembly-CSharp.zip) SW: dnSpy 需要增加unity引擎引用
太感谢了，除了这些脚本文件，完整的unity项目文件您还有吗

**Comment by HackEFA** [comment]
那个你download下来dll就行，unity3D软件向导配置就可以加载需要的那部分插件，主要内容在这个C#里面。
可以参考https://www.youtube.com/watch?v=MQKJfZCAEa8
我并没有这个项目的全部工程，要看大佬是否开源了，C#这部分是主要机械臂实现的主要部分和接口。

nishiwodelian ***@***.***> 于2021年10月14日周四 下午8:37写道：

**Comment by Ice-Panda** [comment]
> > 好的，那我明白了，谢谢你
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "peng-zhihui/Dummy-Robot" _**@**_._**>; 发送时间: 2021年10月14日(星期四) 晚上9:35 _**@**_.**_>; _**@**_._**>;"State _**@**_.**_>; 主题: Re: [peng-zhihui/Dummy-Robot] 偶像能不能把上位机软件的项目代码也开源呀，想要学习学习 (#54) 是的，比较简单，就是基本的串口通信和步态实现，你自己学习下可以用unity3D尝试做一下 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> HackEFA说的是正确的，上位机主要就是串口通信和模型可视化（当然后面我会添加很多扩展比如相机标定、手眼标定、Gcode生成等），模型文件我已经提供了你可以自己实现一下，实现方面有技术问题都可以跟我交流的

稚晖君你好，我想请教一下Dummy Studio中，网格地板和右上角的坐标轴是如何实现的，为什么可以和编辑模式下几乎一样。
