### ISSUE TITLE
咨询一下atlas200的开发套件相关的硬件配置。

### ISSUE THREAD

**Issue by wangweiqing** [peng-zhihui/Dummy-Robot#66]
hello，看到动作捕获那部分，使用了双目摄像头加一个atlas200的卡，想咨询一下，那个搭载atlas卡的开发板相关配置是什么？目前有有一些兴趣去做一下这部分相关的东西。

**Comment by peng-zhihui** [comment]
https://e.huawei.com/cn/products/cloud-computing-dc/atlas/atlas-200
不过现在已经没有对外提供了，新一代产品明年会出

**Comment by wangweiqing** [comment]
淘宝上还有存量的产品~只不过主要是4G的版本，8G版本的会比较少。
