### ISSUE TITLE
请教一下，步进如何能像BLDC机械臂一样通过电流环路的控制进而对力进行控制，当前步进电机如何实现这样的效果？

### ISSUE THREAD

**Issue by mailonghua** [peng-zhihui/Dummy-Robot#79]
请教一下，步进如何能像BLDC机械臂一样通过电流环路的控制进而对力进行控制，当前步进电机如何实现这样的效果？
多谢

_Originally posted by @mailonghua in https://github.com/peng-zhihui/Dummy-Robot/issues/77#issuecomment-989757449_

**Comment by mailonghua** [comment]
是斩波驱动芯片来形成一个类电流环路吗？通过pwm/dac控制斩波驱动芯片的vref，然后采集反馈，是这样吗

**Comment by gannerfreer** [comment]
我看着没有采集，应该是用芯片内部的闭环控制的电流

**Comment by peng-zhihui** [comment]
斩波芯片进行电流控制，读一下驱动器源码
